config/routes.rb
Rails.application.routes.draw do
  root to: 'memorandums#index'
  resources :memorandums
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memorandum.rb
class Memorandum < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/memorandums_controller.rb
class MemorandumsController < ApplicationController
  def index
    #@memorandums = Memorandum.all
    #@memorandums = Memorandum.order('id DESC')
    @memorandums = Memorandum.order('id DESC').all.page(params[:page])
    @memorandum = Memorandum.new
  end

  def show
    @memorandum = Memorandum.find(params[:id])
    #/messages/2 と言った URL にアクセスされたときに、 
    #params[:id] = 2 として代入される
  end

  def new
    @memorandum = Memorandum.new
  end

  def create
    
      @memorandum = Memorandum.new(memorandum_params)

    if @memorandum.save
      flash[:success] = 'メモ が正常に投稿されました'
      redirect_to memorandums_path
      
    else
      flash[:danger] = 'メモ が投稿されませんでした'
      redirect_to memorandums_path
    end
  end

  def edit
    @memorandum = Memorandum.find(params[:id])
  end

  def update
    @memorandum = Memorandum.find(params[:id])

    if @memorandum.update(memorandum_params)
      flash[:success] = 'メモは正常に更新されました'
      redirect_to @memorandum
    else
      flash.now[:danger] = 'メモは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @memorandum = Memorandum.find(params[:id])
    @memorandum.destroy

    flash[:success] = 'メモは正常に削除されました'
    redirect_to memorandums_url
  end
  
  private

  # Strong Parameter
  def memorandum_params
    params.require(:memorandum).permit(:content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_memorandums.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Memorandum</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!--<ul class="nav navbar-nav navbar-right">-->
        <!--  <li><%= link_to  '新規メモの投稿', new_memorandum_path %></li>-->
        <!--</ul>-->
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Memorandum</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_memorandums' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/memorandums/_form.html.erb
<div class="row">
  <div class="col-xs-6">
    
    <%= form_for(memorandum) do |f| %>
      <% if memorandum.errors.any? %>
        <div class="alert alert-warning">
          <ul>
            <% memorandum.errors.full_messages.each do |e_msg| %>
              <li><%= e_msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="form-group">
        <%= f.label :content, 'メモ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
    
    
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/memorandums/edit.html.erb
<h1>id: <%= @memorandum.id %> のメモ編集ページ</h1>


<%= render 'form', memorandum: @memorandum %>

app/views/memorandums/index.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6 col-md-offset-2 col-md-8 col-sm-offset-2 col-sm-8 col-xs-12">
    
    <h1>メモ入力欄</h1>
    
    <%= render 'form', memorandum: @memorandum %>
    
    
    <h1>メモ一覧</h1>


    <% if @memorandums.any? %>
      <table class="table table-bordered">
        <thead>
          <tr class="active">
            <th>id</th>
            <th>メモ</th>
            <th>日時</th>
            <th align="center">消去ボタン</th>
          </tr>
        </thead>
        <tbody>
          <% @memorandums.each do |memorandum| %>
            <tr>
              <td><%= link_to memorandum.id, memorandum %></td>
              <td><%= memorandum.content %></td>
              <td><%= memorandum[:created_at].strftime("%Y-%m-%d_%H:%M") %></td>
              <td align="center"><%= link_to '消去', memorandum, method: :delete, data: { confirm: 'タスクを消してよろしいですか?' }, class: 'btn btn-default' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

  </div>
</div>

  <div>
    <%= paginate @memorandums %>
  </div>
<% end %>

app/views/memorandums/new.html.erb
<h1>メモ新規作成ページ</h1>

<%= form_for(@memorandum) do |f| %>
  <%= f.label :content, 'メモ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to '一覧に戻る', memorandums_path %>

app/views/memorandums/show.html.erb
<h1>id = <%= @memorandum.id %> のメモ詳細ページ</h1>

 <table class="table table-bordered">
    <thead>
      <tr class="active">
        <th>id</th>
        <th>メモ</th>
        <th>日時</th>
      </tr>
    </thead>
    <tbody>

        <tr>
          <td><%= @memorandum.id %></td>
          <td><%= @memorandum.content %></td>
          <td><%= @memorandum[:created_at].strftime("%Y-%m-%d_%H:%M") %></td>
        </tr>

    </tbody>
  </table>

<%= link_to 'このメッセージを編集する', edit_memorandum_path(@memorandum), class: 'btn btn-default' %>
<%= link_to 'このメッセージを削除する', @memorandum, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>